### PR TITLE
Legg til lydbok i readme

### PR DESCRIPTION
**Pull request by forteller**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I suspect this link belong to free-culture.cc, not this README.

**Comment by forteller** [comment]
1) Why? This is the best list of different formats to download I found (see 2)). Audiobook is also a format, why list the other English formats but not this one?

2) free-culture.cc is down. I've notified Lessig via Twitter, no idea if he sees it or not.

**Comment by petterreinholdtsen** [comment]
[forteller]
> 1) Why? This is the best list of different formats to download I found
> (see 2)). Audiobook is also a format, why list the other English
> formats but not this one?

Because the README list only the formats created by my book project, not
what others have created.  I did not really want to "take
responsibility" for others presentation of the book, I lack the time to
check the quality.

> 2) free-culture.cc is down. I've notified Lessig via Twitter, no idea
> if he sees it or not.

Oh, that is sad.  Hope it get back online soon.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by forteller** [comment]
> [forteller]
> 1) Why? This is the best list of different formats to download I found (see 2)). Audiobook is also a format, why list the other English formats but not this one?
> Because the README list only the formats created by my book project, not what others have created. I did not really want to "take responsibility" for others presentation of the book, I lack the time to check the quality.

Oh, I see. I just thought it was a list of formats for download in English, and that you just made the Norwegian versions. Then I agree :)

> 2) free-culture.cc is down. I've notified Lessig via Twitter, no idea if he sees it or not.
> Oh, that is sad. Hope it get back online soon.

He replied, so I hope he's working on it.

> […](#)
> -- Happy hacking Petter Reinholdtsen

**Pull request closed without merging**
